function h = plotFrame(varargin)
%PLOTFRAME Plot a given frame
%   Plots the x, y, and z axes of the frame given by a
%   transform matrix "T" on a figure "f", with the length given by
%   axisLength (1 by default) and the name given by frameName. If the
%   objective is to update an already represented plot, the handler of the
%   plot can be introduced in "plotHandler".
%   If no frame name is to be plotted, insert 0
%   If no plot handler is to be used, insert []
%   USAGE: 
%       h = plotFrame(T)
%       h = plotFrame(T, axisLength)
%       h = plotFrame(T, axisLength, frameName)
%       h = plotFrame(T, axisLength, frameName, plotHandler)
%       h = plotFrame(T, axisLength, frameName, plotHandler, figure)

    switch nargin
        case 1
            T = varargin{1};
            axisLength = 1;
            frameName = 0;
            plotHandler = [];
            f = [];
        case 2
            T = varargin{1};
            axisLength = varargin{2};
            frameName = 0;
            plotHandler = [];
            f = [];
        case 3
            T = varargin{1};
            axisLength = varargin{2};
            frameName = varargin{3};
            plotHandler = [];
            f = [];
        case 4
            T = varargin{1};
            axisLength = varargin{2};
            frameName = varargin{3};
            plotHandler = varargin{4};
            f = [];
        case 5
            T = varargin{1};
            axisLength = varargin{2};
            frameName = varargin{3};
            plotHandler = varargin{4};
            f = varargin{5};
        otherwise
            cprintf('err','Wrong number of input arguments. Usage:\n')
            cprintf('err','    plotFrame(T)\n')
            cprintf('err','    plotFrame(T, figure)\n')
            cprintf('err','    plotFrame(T, figure, axisLength)\n')
            cprintf('err','    plotFrame(T, figure, axisLength, frameName)\n')
            error('Wrong number of input arguments');    
    end
    
    if size(T) ~= [4 4]
        error('Input transformation matrix is not 4x4');
    end
    
    origin = T(1:3,4);
    xaxis = T(1:3,1)*axisLength;
    yaxis = T(1:3,2)*axisLength;
    zaxis = T(1:3,3)*axisLength;
    
    if size(plotHandler)
        h = plotHandler;
        if size(f)
            figure(f);  
        end
        
        set(h(1),'XData',origin(1),...
                 'YData',origin(2),...
                 'ZData',origin(3),...
                 'UData',xaxis(1),...
                 'VData',xaxis(2),...
                 'WData',xaxis(3),...
                 'Color', 'r','LineWidth', 2, 'MaxHeadSize', 0.5);
             
        set(h(2),'XData',origin(1),...
                 'YData',origin(2),...
                 'ZData',origin(3),...
                 'UData',yaxis(1),...
                 'VData',yaxis(2),...
                 'WData',yaxis(3),...
                 'Color', 'g','LineWidth', 2, 'MaxHeadSize', 0.5);
             
        set(h(3),'XData',origin(1),...
                 'YData',origin(2),...
                 'ZData',origin(3),...
                 'UData',zaxis(1),...
                 'VData',zaxis(2),...
                 'WData',zaxis(3),...
                 'Color', 'c','LineWidth', 2, 'MaxHeadSize', 0.5);
             
        if isstring(frameName)||ischar(frameName)
            set(h(4),'Position',[origin(1)+0.05*axisLength,...
                                 origin(2)+0.05*axisLength,...
                                 origin(3)+0.05*axisLength],...
                     'String',strcat('\{', frameName, '\}'),...
                     'Interpreter','latex');                     

            set(h(5),'Position',[origin(1)+xaxis(1)*(1+0.03*axisLength),...
                                 origin(2)+xaxis(2)*(1+0.03*axisLength),...
                                 origin(3)+xaxis(3)*(1+0.03*axisLength)],...
                     'String',strcat('$x_{', frameName, '}$'),...
                     'Interpreter','latex');
                    
            set(h(6),'Position',[origin(1)+yaxis(1)*(1+0.03*axisLength),...
                                 origin(2)+yaxis(2)*(1+0.03*axisLength),...
                                 origin(3)+yaxis(3)*(1+0.03*axisLength)],...
                     'String',strcat('$y_{', frameName, '}$'),...
                     'Interpreter','latex');
                    
            set(h(7),'Position',[origin(1)+zaxis(1)*(1+0.03*axisLength),...
                                 origin(2)+zaxis(2)*(1+0.03*axisLength),...
                                 origin(3)+zaxis(3)*(1+0.03*axisLength)],...
                     'String',strcat('$z_{', frameName, '}$'),...
                     'Interpreter','latex');
        end
    else
        if size(f)
            figure(f);  
        end
        h(1) = quiver3(origin(1), origin(2), origin(3),...
                       xaxis(1), xaxis(2), xaxis(3),...
                       'Color', 'r','LineWidth', 2, 'MaxHeadSize', 0.5);
        hold on;
        h(2) = quiver3(origin(1), origin(2), origin(3),...
                       yaxis(1), yaxis(2), yaxis(3),...
                       'Color', 'g','LineWidth', 2, 'MaxHeadSize', 0.5);
        h(3) = quiver3(origin(1), origin(2), origin(3),...
                       zaxis(1), zaxis(2), zaxis(3),...
                       'Color', 'c','LineWidth', 2, 'MaxHeadSize', 0.5);
        if isstring(frameName)||ischar(frameName)
            h(4) = text(origin(1)+0.05*axisLength,...
                        origin(2)+0.05*axisLength,...
                        origin(3)+0.05*axisLength,...
                        strcat('\{', frameName, '\}'),'Interpreter','latex');
            h(5) = text(origin(1)+xaxis(1)*(1+0.03*axisLength),...
                        origin(2)+xaxis(2)*(1+0.03*axisLength),...
                        origin(3)+xaxis(3)*(1+0.03*axisLength),...
                        strcat('$x_{', frameName, '}$'),'Interpreter','latex');
            h(6) = text(origin(1)+yaxis(1)*(1+0.03*axisLength),...
                        origin(2)+yaxis(2)*(1+0.03*axisLength),...
                        origin(3)+yaxis(3)*(1+0.03*axisLength),...
                        strcat('$y_{', frameName, '}$'),'Interpreter','latex');
            h(7) = text(origin(1)+zaxis(1)*(1+0.03*axisLength),...
                        origin(2)+zaxis(2)*(1+0.03*axisLength),...
                        origin(3)+zaxis(3)*(1+0.03*axisLength),...
                        strcat('$z_{', frameName, '}$'),'Interpreter','latex');
        end
    end
end
